version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: datawow-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: concert_db
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: datawow-backend
    restart: always
    ports:
      - 3001:3001
    environment:
      DATABASE_URL: postgresql://root:password123@db:5432/concert_db?schema=public
      JWT_SECRET: supersecretkey
      PORT: "3001"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: datawow-frontend
    restart: always
    ports:
      - 3000:3000
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    depends_on:
      - backend

volumes:
  postgres_data:
